export const UPLOAD_REQUESTING = 'UPLOAD_REQUESTING';
export const LOAD_ALL_PROFILE_FILES = 'LOAD_ALL_PROFILE_FILES';
export const LOAD_FILE_REQUESTING = 'LOAD_FILE_REQUESTING';
export const DELETE_FILE_REQUESTING = 'DELETE_FILE_REQUESTING';
export const DELETE_FILES_REQUESTING = 'DELETE_FILES_REQUESTING';
export const CHANGE_FILE_SORTORDER_REQUESTING = 'CHANGE_FILE_SORTORDER_REQUESTING';
