export const LOGIN_REQUESTING = 'LOGIN_REQUESTING';
export const LOGOUT_REQUESTING = 'LOGOUT_REQUESTING';
export const REGISTER_REQUESTING = 'REGISTER_REQUESTING';
export const USER_SAVE_PREFERENCES = 'USER_SAVE_PREFERENCES';
export const USER_UPDATE_FIELDS = 'USER_UPDATE_FIELDS';
export const USER_UPDATE_FIELDS_SILENT = 'USER_UPDATE_FIELDS_SILENT';
export const USER_DELETE_USER = 'USER_DELETE_USER';
