export const CHAT_SEARCH = 'CHAT_SEARCH';
export const CHAT_CANCEL_SEARCH = 'CHAT_CANCEL_SEARCH';

export const CHAT_SEARCH_AGE_MIN = 12;
export const CHAT_SEARCH_AGE_MAX = 90;
export const CHAT_SEARCH_NAME_LENGTH_MIN = 3; // minimum characters to start name search
export const CHAT_SEARCH_DISTANCE_MAX_KM = 805;

export const CHAT_FETCH_PROFILE_IMAGES = 'CHAT_FETCH_PROFILE_IMAGES';
export const CHAT_CANCEL_FETCH_PROFILE_IMAGES = 'CHAT_CANCEL_FETCH_PROFILE_IMAGES';

export const CHAT_SOCKET_MESSAGE_RECEIVED = 'CHAT_SOCKET_MESSAGE_RECEIVED';
export const CHAT_SOCKET_POST_MESSAGE_READ = 'CHAT_SOCKET_POST_MESSAGE_READ';

export const CHAT_CHAT_MESSAGE_SEND = 'CHAT_CHAT_MESSAGE_SEND';
export const CHAT_FETCH_CHAT_MESSAGES = 'CHAT_FETCH_CHAT_MESSAGES';
export const CHAT_CANCEL_FETCH_MESSAGES = 'CHAT_CANCEL_FETCH_MESSAGES';

export const CHAT_POST_UPDATE_PROFILE_RELATION = 'CHAT_POST_UPDATE_PROFILE_RELATION';

export const CHAT_WHISPER = 'CHAT_WHISPER';
